---
- hosts: all
  remote_user: admin
  become: yes
  tasks: 
        - name: Install basic packages
          yum: name={{ item }} state=present
          with_items:
                - mtr
                - iputils.x86_64
                - iproute.x86_64
                - nmap.x86_64
                - tcpdump.x86_64
                - net-tools.x86_64  
                - tree
                - vim

